---
# These tasks install http and the Git client.

- name: Install and configure apache and Git client
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - git

- name: Copying the index.html page to remote server
  template: src=index.raw.html dest=/var/www/html/index.html
  mode: 0644

- name: Starting and enabling the http service
  service: name=httpd state=started enabled=yes
