---
# These tasks install http and the Git client.

- name: Install and configure apache and Git client
  yum: name={{ item }} state=absent
  with_items:
   - httpd
   - git

- name: Copy the index.html file
  copy: src=index.raw.html dest=/var/www/html/index.html

#- name: Starting and enabling the http service
#  service: name=httpd state=started enabled=yes
