---
# This playbook transfers and executes shell script.

- name: transfer & execute shell script
  hosts: all
  remote_user: root
  sudo: yes
  tasks:
    - name: Transfer the script
       copy: src=test.sh dest=/root mode=0777

    - name: Execute the script
       command: sh /root/test.sh
